### ISSUE TITLE
ExtendScript doesn't run in zxp installed extension

### ISSUE THREAD

**Issue by ikrupnov** [hyperbrew/bolt-cep#85] opened 2023-06-28 13:17 UTC
I have some scripts in _aeft.ts_ so I run them with _evalTS()_ from a button in my vue component. It works perfectly while I'm in the dev mode (_yarn dev_), even if I do build it still works. The problem appears on another machine if I install my extension from _.zxp_ file there. The scripts just don't run. Also I have external scripts from _.jsx_ files to run with _evalFile()_ and they run ok.
If I pull my code, install all the dependencies and do _yarn dev_ on that machine the scripts start to run. Moreover they start to run from _.zxp_ version as well but stop after I restart AE.
I assume I could have done something wrong but I haven't found out anything from the Readme.
What can cause this problem?

**Comment by justintaylor-dev** [comment] 2023-06-28 23:23
If the issue is happening on another machine but not yours then the problem is likely their version of the AE or a clash with some other tool they have. Since this isn't an error with Bolt, I'm closing the issue, but feel free to move the question to our Discord for general discussion around Bolt CEP development:

https://discord.com/invite/PC3EvvuRbc

**Closed** 2023-06-28 23:23 UTC
